### PR TITLE
Update Terraform to version 0.12.31

### PR DESCRIPTION
**Pull request by ajmaddaford**
### What is the context of this PR?
Updates the pinned Terraform version to 0.12.31 to fix provider issues caused by a Hashicorp
GPG key leak.

https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570

### How to review 
- Deploy the Terraform to a GCP environment
- Ideally deploy over an existing environment to check that no conflicts arise

### CODE REVIEW

**Review by MebinAbraham — COMMENTED** [review]
Our infrastructure base image only installs 0.11.8 & 0.12.17, therefore for this repo, we need to remove the `tfenv use "$(< .terraform-version)"` from the deploy and destroy scripts as it currently fails due to `No installed versions of terraform matched '0.12.31'`. We should look at making a decisions of whether we want to not install any version in the base image and pull it at run time, or preinstall all required versions (minimises risk).

For other envs, we don't expliciallty call `tfenv use` but they work because on init it can pull down the required version if you have a `.terraform-version` file.
i.e
```
version '0.12.31' is not installed (set by /tmp/build/f983d776/eq-terraform-gcp/.terraform-version). Installing now as TFENV_AUTO_INSTALL==true
```

**Comment by pricem14pc** [comment]
> Our infrastructure base image only installs 0.11.8 & 0.12.17, therefore for this repo, we need to remove the `tfenv use "$(< .terraform-version)"` from the deploy and destroy scripts as it currently fails due to `No installed versions of terraform matched '0.12.31'`.
> 
> For other envs, we don't expliciallty call `tfenv use` but they work because on init it can pull down the required version if you have a `.terraform-version` file.
> i.e
> 
> ```
> version '0.12.31' is not installed (set by /tmp/build/f983d776/eq-terraform-gcp/.terraform-version). Installing now as TFENV_AUTO_INSTALL==true
> ```
> 
> We should look at making a decisions of whether we want to not install any version in the base image and pull it at run time, or preinstall all required versions (minimises risk).

Feels like for speed and control (security) the image should have all required versions for a given point in time installed. It does introduce more of a dependency though

**Comment by ajmaddaford** [comment]
I have raised a pull request to replace the Terraform versions in the build image with 0.12.31 and 0.14.11 - https://github.com/ONSdigital/eq-infrastructure-deploy-image/pull/5

I have also set TFENV_AUTO_INSTALL=false so that Terraform is not auto-downloaded and installed when it doesn't exist in the base image. As that is now set I have removed the redundant `tfenv use` command from the deploy and destroy scripts.

**Review by MebinAbraham — APPROVED** [review]
Working as expected now 👍

**Review by JamesGardiner — APPROVED** [review]

**Pull request merged**
